apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rvqksuuva-python 
  janus-idp.io/tekton: rvqksuuva-python
  backstage.io/kubernetes-id: rvqksuuva-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rvqksuuva-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml